#!/usr/bin/env python3
"""
sync_applied.py -- tell the watcher which roles you've already applied to
(or skipped), without publishing that list.

Reads the private job-search/applications.md (gitignored) and writes
applied.json: short hashes of each role's URL and company|title, plus its
status. No names or URLs go into the file. watcher.py hashes every posting the
same way, and roles you've applied to or skipped stop showing up in the hourly
email, the closing-soon block, priority alerts and TOP_PICKS.md. Roles marked
`prepared` stay visible with a "resume ready, not sent" tag.

    python3 sync_applied.py          # then: git add applied.json && git commit && git push

Run it after applying to things (the /apply skill can do it for you).
"""
import json
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
try:
    import requests  # noqa: F401  (watcher imports it; not needed here)
except ImportError:
    import types
    sys.modules["requests"] = types.ModuleType("requests")
from watcher import _h, _role_sig, _ukey  # same normalization as the watcher  # noqa: E402

APPS = os.path.join(HERE, "job-search", "applications.md")
OUT = os.path.join(HERE, "applied.json")

HEAD_RE = re.compile(r"^#{2,3} (.+?) — (.+)$")
STATUS_RE = re.compile(r"^- Status:\s*`?([a-z-]+)`?(.*)$", re.I)
URL_RE = re.compile(r"^- URL:\s*(\S+)")
SKIP_SECTIONS = re.compile(r"^(integrity|batch triage|\d{4}-\d{2}-\d{2})", re.I)
RANK = {"skipped": 1, "prepared": 2, "applied": 3, "interview": 4, "offer": 5}


def classify(status, rest):
    s = status.lower()
    if s in ("applied", "interview", "offer", "rejected"):
        return "applied"          # rejected still means: don't alert me again
    if s == "prepared":
        return "prepared"
    if s == "skipped" or (s == "watching" and re.search(r"skip|not eligible|screen-?out", rest, re.I)):
        return "skipped"
    return ""


def parse(text):
    entries, cur = [], None
    for line in text.splitlines():
        m = HEAD_RE.match(line)
        if m or line.startswith("## "):
            if cur:
                entries.append(cur)
            cur = None
            if m and not SKIP_SECTIONS.match(m.group(1)):
                company = re.sub(r"\s*\((?!.*\d).*?\)\s*$", "", m.group(1)).strip()
                cur = {"company": company, "title": m.group(2).strip(), "status": "", "url": ""}
            continue
        if not cur:
            continue
        sm = STATUS_RE.match(line.strip())
        if sm and not cur["status"]:
            cur["status"] = classify(sm.group(1), sm.group(2))
        um = URL_RE.match(line.strip())
        if um and not cur["url"] and "search" not in line:
            cur["url"] = um.group(1)
    if cur:
        entries.append(cur)
    return [e for e in entries if e["status"]]


def main():
    try:
        text = open(APPS, encoding="utf-8").read()
    except OSError:
        sys.exit(f"Can't read {APPS}")
    entries = parse(text)
    hashes = {}
    for e in entries:
        keys = [_role_sig(e["company"], e["title"])]
        if e["url"]:
            keys.append(_ukey(e["url"]))
        for k in keys:
            h = _h(k)
            if RANK.get(e["status"], 0) > RANK.get(hashes.get(h, ""), 0):
                hashes[h] = e["status"]
    data = {"updated": time.strftime("%Y-%m-%d"),
            "note": "Hashes only, generated by sync_applied.py from a private tracker.",
            "h": dict(sorted(hashes.items()))}
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=1)
        fh.write("\n")
    counts = {}
    for e in entries:
        counts[e["status"]] = counts.get(e["status"], 0) + 1
    print(f"applied.json: {len(entries)} roles ("
          + ", ".join(f"{v} {k}" for k, v in sorted(counts.items())) + f"), {len(hashes)} hashes.")
    if "-v" in sys.argv:
        for e in entries:
            print(f"  {e['status']:9} {e['company']} — {e['title']}")


if __name__ == "__main__":
    main()
